spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://containers-us-west-170.railway.app:6911/railway
    username: postgres
    password: FQAnQhB8vDdVUL2eKfAs
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop